DROP TABLE IF EXISTS hits;

CREATE TABLE IF NOT EXISTS hits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    app VARCHAR(255) NOT NULL,
    uri VARCHAR(512) NOT NULL,
    ip  VARCHAR(45),
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX idx_hits_timestamp ON hits (timestamp);
CREATE INDEX idx_hits_uri ON hits (uri);
CREATE INDEX idx_hits_timestamp_uri ON hits (timestamp, uri);